### ISSUE TITLE
Reestruturación do proxecto.

### ISSUE THREAD

**Issue by lauramcastro** [alopezsanchez/vvs-practicatesting#2]
Non ten moito sentido que o contido do proxecto estea na subcarpeta "vvs-project"; eliminade ese nivel. Ademais, o UML (parabéns por incluílo!! está totalmente actualizado?) debería ir na carpeta doc, onde non é necesario que fagades commit do JavaDoc (calquera cousa que poida xerarse a partir do contido do repositorio non debería consumir espazo nin recursos cada vez que facemos operacións co repositorio).

**Comment by adrianleira** [comment]
Dos trabajando en este issue. Andrea Ardións actualiza el UML y yo elevo de nivel el proyecto.

**Comment by lauramcastro** [comment]
:+1: Muy bien; lamentablemente GitHub sólo permite asignar un issue a una única persona, pero podéis hacer que cualquier colaborador/a se vea implicado en una _issue_ mencionando su nombre en un comentario precedido de una arroba (@), así: @lauramcastro, @adrianleira, @andreaardions. Si no me equivoco, esto hace que le lleguen notificaciones con nuevos mensajes, cambios de etiquetado de la _issue_, etc. No es lo mismo que ser el _assignee_, pero te convierte en _participant_, que es algo.

**Comment by adrianleira** [comment]
Proyecto subido de nivel y ordenado. A la espera de subir el diagrama actualizado.

**Comment by andreaardions** [comment]
Diagrama UML actualizado a la implementación más reciente.
