### ISSUE TITLE
Refactorizar proyecto

### ISSUE THREAD

**Issue by adrianudc** [alopezsanchez/vvs-practicatesting#3]
Hola,

Sólo veo dos subcarpetas en el proyecto, y en ellas están mezcladas interfaces con sus implementaciones. Sería más claro si las implementaciones de una interfaz descienden del paquete de la interfaz.

Además, el nombre de las implementaciones de las interfaces no da pie a interpretar que es una implementación, si no un POJO normal.

**Comment by alopezsanchez** [comment]
Solucionado.

Gracias!
