### ISSUE TITLE
Error especificación interfaz Servidor y discrepancia con diagrama UML

### ISSUE THREAD

**Issue by ymishchenko** [alopezsanchez/vvs-practicatesting#5]
Habéis llamado Servicio a la interfaz correspondiente a la interfaz Servidor de la especificación original, lo que supone un discrepancia respecto al enunciado y al diagrama UML actual, en el cual la interfaz está correctamente llamada Servidor.

**Comment by andreaardions** [comment]
¡Gracias!

Ya hemos renombrado el Servicio por Servidor tanto en la implementación como en el diagrama UML.
