### ISSUE TITLE
Faltan tests de Servidor

### ISSUE THREAD

**Issue by ymishchenko** [alopezsanchez/vvs-practicatesting#6]
No tenéis tests para probar las implementaciones de Servidor.

**Comment by eloynaveira** [comment]
Tests para servidor realizados.

**Comment by lauramcastro** [comment]
Que conste que la presencia/ausencia de pruebas no era uno de los elementos a juzgar en el análisis del repositorio del otro equipo, ya que no se pedían en la S1.
